BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Lists" (
	"Id"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Description"	TEXT NOT NULL,
	CONSTRAINT "PK_Lists" PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Subtasks" (
	"Id"	INTEGER NOT NULL,
	"Text"	TEXT NOT NULL,
	"IsComplete"	INTEGER NOT NULL,
	"Description"	TEXT NOT NULL,
	"TaskId"	INTEGER NOT NULL,
	CONSTRAINT "PK_Subtasks" PRIMARY KEY("Id" AUTOINCREMENT),
	CONSTRAINT "FK_Subtasks_Tasks_TaskId" FOREIGN KEY("TaskId") REFERENCES "Tasks"("Id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Tags" (
	"Id"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	CONSTRAINT "PK_Tags" PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TaskTags" (
	"TaskId"	INTEGER NOT NULL,
	"TagId"	INTEGER NOT NULL,
	CONSTRAINT "PK_TaskTags" PRIMARY KEY("TaskId","TagId"),
	CONSTRAINT "FK_TaskTags_Tags_TagId" FOREIGN KEY("TagId") REFERENCES "Tags"("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_TaskTags_Tasks_TaskId" FOREIGN KEY("TaskId") REFERENCES "Tasks"("Id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Tasks" (
	"Id"	INTEGER NOT NULL,
	"Text"	TEXT NOT NULL,
	"IsComplete"	INTEGER NOT NULL,
	"Description"	TEXT NOT NULL,
	"ListId"	INTEGER NOT NULL,
	"TagId"	INTEGER NOT NULL DEFAULT 0,
	CONSTRAINT "PK_Tasks" PRIMARY KEY("Id" AUTOINCREMENT),
	CONSTRAINT "FK_Tasks_Lists_ListId" FOREIGN KEY("ListId") REFERENCES "Lists"("Id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
	"MigrationId"	TEXT NOT NULL,
	"ProductVersion"	TEXT NOT NULL,
	CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY("MigrationId")
);
CREATE TABLE IF NOT EXISTS "__EFMigrationsLock" (
	"Id"	INTEGER NOT NULL,
	"Timestamp"	TEXT NOT NULL,
	CONSTRAINT "PK___EFMigrationsLock" PRIMARY KEY("Id")
);
INSERT INTO "__EFMigrationsHistory" VALUES ('20250921140308_InitialCreate','9.0.9');
INSERT INTO "__EFMigrationsHistory" VALUES ('20250921143841_InitialCreatev0.2','9.0.9');
INSERT INTO "__EFMigrationsHistory" VALUES ('20250921152458_ver0.3','9.0.9');
CREATE INDEX IF NOT EXISTS "IX_Subtasks_TaskId" ON "Subtasks" (
	"TaskId"
);
CREATE INDEX IF NOT EXISTS "IX_TaskTags_TagId" ON "TaskTags" (
	"TagId"
);
CREATE INDEX IF NOT EXISTS "IX_Tasks_ListId" ON "Tasks" (
	"ListId"
);
COMMIT;
